name: test-ci

on:
  push:
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: make test
      - run: make lint